let people = ["Greg", "Mary", "Devon", "James"];
console.log(people);
people.shift();
console.log(people);
people.unshift("Matt");
console.log(people);
people.pop();
console.log(people);
people.push("Lukas");
console.log(people);
let peopleCopy = people.slice(2);
console.log(peopleCopy);
console.log(people);
console.log(people.indexOf("Mary"));
console.log(people.indexOf("Foo"));
people = ["Greg", "Mary", "Devon", "James"];
console.log(people);
people.splice(2,1, "Elizabeth", "Anna");
console.log(people);